"""
Exception Explanation Agent for Ledgr (Part 3.3)
Powered by Groq's OpenAI-compatible inference with model openai/gpt-oss-120b.
Explains flagged/mismatched financial records with structured Pydantic output.
Includes 8s timeout, circuit-breaker retry cap (max 1), and explicit fallback:
explanation_status: 'unavailable' -> routes to manual review.
"""

import os
import sys
import json
import logging
from pathlib import Path
from typing import Dict, Any, Optional
from pydantic import BaseModel, Field

from dotenv import load_dotenv
load_dotenv()

# Ensure project root in sys.path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("ledgr.agents.explain")

GROQ_MODEL = os.getenv("LEDGR_GROQ_MODEL", "openai/gpt-oss-120b")
GROQ_TIMEOUT_SECONDS = float(os.getenv("LEDGR_GROQ_TIMEOUT", "8.0"))


class ExceptionExplanation(BaseModel):
    """Structured output schema for exception explanation."""
    explanation: str = Field(
        description="Clear, plain-language description of the discrepancy, grounded strictly in provided facts."
    )
    suggested_resolution: str = Field(
        description="Actionable recommendation for the finance controller to confirm or reject the match."
    )
    confidence_reasoning: str = Field(
        description="Detailed justification for the assigned confidence score and what evidence would resolve ambiguity."
    )
    explanation_status: str = Field(
        default="ok",
        description="'ok' if generated by live Groq LLM; 'unavailable' if timed out/unreachable and routed to manual review."
    )


SYSTEM_PROMPT = """You are the Ledgr Financial Exception Reasoning Agent.
Your role is to analyze discrepancies between financial records (bank statements vs payment gateway settlements vs internal ledgers) and provide clear, precise explanations and actionable resolution recommendations for a finance controller.

Strict Operating Rules:
1. ONLY reference facts and numbers explicitly present in the provided records and rule verifier breakdown. NEVER invent transaction details, fee schedules, or external events.
2. If the amount delta resembles a typical gateway fee (1-2% or flat fee), explicitly identify it as a fee candidate.
3. If there is a date discrepancy, evaluate whether it falls within normal settlement lags (T+1, T+2).
4. Clearly state what specific action or verification would resolve the discrepancy.
5. Respond naturally in clear English, or in natural Hinglish if the context or prompt is phrased in Hinglish.
6. You MUST respond with a valid JSON object matching the requested schema:
   {
     "explanation": "...",
     "suggested_resolution": "...",
     "confidence_reasoning": "..."
   }
"""


def generate_fallback_explanation(
    record_a: Dict[str, Any],
    record_b: Dict[str, Any],
    match_details: Dict[str, Any],
    error_msg: str = "Groq inference service unreachable or timed out."
) -> ExceptionExplanation:
    """
    Deterministic rule-based fallback when Groq is unavailable or times out.
    Guarantees no silent failures: explanation_status is explicitly marked 'unavailable'.
    """
    amt_a = record_a.get("amount", 0.0)
    amt_b = record_b.get("amount", 0.0)
    delta = round(abs(amt_a - amt_b), 2)
    conf = match_details.get("confidence", 50)
    rule_breakdown = match_details.get("rule_breakdown", {})
    amt_detail = rule_breakdown.get("amount", {}).get("detail", {})
    is_fee = amt_detail.get("is_fee_candidate", False)

    if is_fee:
        expl = (
            f"Amount differs by ₹{delta:,.2f} (Source A ₹{amt_a:,.2f} vs Source B ₹{amt_b:,.2f}), "
            f"consistent with gateway fee deduction at source. Date lag recorded. "
            f"Confidence is {conf}%. [LLM explanation service unavailable: {error_msg}]"
        )
        res = "Confirm gateway fee deduction in settlement schedule and approve match."
        reason = f"Deterministic rule verifier identified fee tolerance pattern (delta ₹{delta:,.2f})."
    elif delta > 0.01:
        expl = (
            f"Amount discrepancy of ₹{delta:,.2f} detected between Source A (₹{amt_a:,.2f}) and Source B (₹{amt_b:,.2f}). "
            f"Discrepancy exceeds standard processing fee tolerance. Confidence is {conf}%. "
            f"[LLM explanation service unavailable: {error_msg}]"
        )
        res = "Escalate for manual investigation with counter-party / vendor records."
        reason = f"Unexplained delta of ₹{delta:,.2f} flagged by deterministic amount rule."
    else:
        expl = (
            f"Records share identical amount ₹{amt_a:,.2f}, but reference or date alignment fell below auto-match threshold. "
            f"Confidence is {conf}%. [LLM explanation service unavailable: {error_msg}]"
        )
        res = "Review counterparty reference and approve if underlying transaction is identical."
        reason = "Amount verified exact; secondary reference/timing ambiguity requires human confirmation."

    return ExceptionExplanation(
        explanation=expl,
        suggested_resolution=res,
        confidence_reasoning=reason,
        explanation_status="unavailable"
    )


def explain_exception(
    record_a: Dict[str, Any],
    record_b: Dict[str, Any],
    match_details: Dict[str, Any]
) -> ExceptionExplanation:
    """
    Escalates an ambiguous/mismatched record pair to Groq openai/gpt-oss-120b.
    Implements 8s timeout, circuit-breaker retry cap (max 1), and structured output validation.
    """
    from agents.groq_client import call_groq_chat_completion, is_groq_circuit_open

    if is_groq_circuit_open():
        return generate_fallback_explanation(
            record_a, record_b, match_details, error_msg="Groq rate limit circuit breaker active"
        )

    user_payload = {
        "record_a": {
            "id": record_a.get("id"),
            "amount": record_a.get("amount"),
            "date": record_a.get("date"),
            "description": record_a.get("description"),
            "reference": record_a.get("reference")
        },
        "record_b": {
            "id": record_b.get("id"),
            "amount": record_b.get("amount"),
            "date": record_b.get("date"),
            "description": record_b.get("description"),
            "reference": record_b.get("reference")
        },
        "match_confidence": match_details.get("confidence"),
        "rule_verification": match_details.get("rule_breakdown")
    }

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {
            "role": "user",
            "content": f"Analyze this reconciliation discrepancy and explain it:\n{json.dumps(user_payload, indent=2)}"
        }
    ]

    data = call_groq_chat_completion(
        messages=messages,
        model=GROQ_MODEL,
        json_mode=True,
        temperature=0.1,
        max_tokens=1500,
        timeout=GROQ_TIMEOUT_SECONDS
    )

    if data and isinstance(data, dict) and data.get("explanation"):
        return ExceptionExplanation(
            explanation=data.get("explanation", ""),
            suggested_resolution=data.get("suggested_resolution", ""),
            confidence_reasoning=data.get("confidence_reasoning", ""),
            explanation_status="ok"
        )

    # Demonstrable fallback behavior: mark unavailable and route to manual review
    return generate_fallback_explanation(
        record_a, record_b, match_details, error_msg="Groq unreachable or rate limited"
    )


if __name__ == "__main__":
    # Test fallback flow
    ra = {"id": "BNK-8814", "amount": 9320.0, "date": "2026-09-01", "description": "Inward credit", "reference": "REF-91824C"}
    rb = {"id": "GW-1023", "amount": 9308.0, "date": "2026-09-02", "description": "Late settlement 1 day", "reference": "PO-991884"}
    md = {"confidence": 71, "rule_breakdown": {"amount": {"detail": {"is_fee_candidate": True}}}}
    
    res = explain_exception(ra, rb, md)
    print("Self-test result:")
    print(res.model_dump_json(indent=2))
